@service_host=http://localhost:8080
@bff_host=http://localhost:8085


## Métricas
GET {{service_host}}/actuator/prometheus


## Obter token
POST {{service_host}}/api/auth/token
Content-Type: application/json
{
    "clientId": "bff",
    "clientSecret": "averylongandsecureclientsecret"
}

## Exemplo de request atutenticado 
GET {{service_host}}/api/v1/rates
Authorization: Bearer ...

GET {{service_host}}/api/v1/loans/6

POST {{service_host}}/api/v1/loans
Content-Type: application/json
{
    "name": "Loan CP",
    "description": "Teste Post Example",
    "value": 100.5,
    "installmentsNumber": 5,
    "startDate": "2024-01-10T00:00:00",
    "rate": {
        "id": 1
    }
}


## Exemplos BFF
GET {{bff_host}}/api/rates

GET {{bff_host}}/api/loans

GET {{bff_host}}/api/loans/6

POST {{bff_host}}/api/loans
{
    "name": "Loan CPl",
    "description": "Teste Post Example",
    "value": 100.5,
    "installmentsNumber": 5,
    "startDate": "2024-01-10T00:00:00",
    "rate": {
        "id": 1
    }
}